NAME = push_swap

SOURCES = push_swap_utils/utils_0.c \
			push_swap_utils/utils_1.c \
			push_swap_utils/utils_2.c \
			push_swap_utils/utils_t_list_0.c \
			push_swap_utils/utils_t_list_1.c \
			push_swap_utils/utils_t_list_2.c \
			push_swap_instructions/instructions_0.c \
			push_swap_instructions/instructions_1.c \
			push_swap_instructions/instructions_2.c \
			check_argv.c \
			simple_sort.c \
			radix_sort.c \
			push_swap.c \

OBJECTS = ${SOURCES:.c=.o}

CC = gcc
CFLAGS = -Wall -Wextra -Werror

RM = rm -rf

all: ${NAME} ${CHECK}

${NAME}: ${OBJECTS}
	@${CC} ${CFLAGS} ${OBJECTS} -o ${NAME}

clean:
	@${RM} ${OBJECTS}

fclean: clean
	@${RM} ${NAME}

re: fclean all

.PHONY: all clean fclean re